//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public string LlaveHash { get; set; }
        public string IdEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> HoraEntrada { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public Nullable<decimal> HorasTrabajadas { get; set; }
        public string EstadoJornada { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
