//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoletaPago
    {
        public int IdBoleta { get; set; }
        public string IdEmpleado { get; set; }
        public string MesCorrespondiente { get; set; }
        public decimal Salario { get; set; }
        public decimal Bonos { get; set; }
        public decimal Descuentos { get; set; }
        public System.DateTime FechaEmision { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
