//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialSalarial
    {
        public int IdHistorial { get; set; }
        public string IdEmpleado { get; set; }
        public decimal Monto { get; set; }
        public string TipoModificacion { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public string MotivoJustificacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
