//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPermiso
    {
        public int IdSolicitud { get; set; }
        public string IdEmpleado { get; set; }
        public string TipoPermiso { get; set; }
        public int NivelPrioridad { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string EstadoAprobacion { get; set; }
        public string MotivoDetallado { get; set; }
        public string RutaComprobante { get; set; }
        public decimal CantidadHoras { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
